# fonts
tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"

# user home dir for brew install --cask
cask_args appdir: "~/Applications", require_sha: true
cask "alfred"
cask "omnifocus"
# istat menus fails to install due to no sha256 associated with the pkg
# cask "istat-menus"

brew "starship"
brew "emacs"
brew "stow"
