# fonts
tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"

# emacs-plus
# https://github.com/d12frosted/homebrew-emacs-plus
tap "d12frosted/emacs-plus"
brew "d12frosted/emacs-plus/emacs-plus@29", args: ["with-native-comp", "with-savchenkovaleriy-big-sur-icon"]

# user home dir for brew install --cask
cask_args appdir: "~/Applications", require_sha: true
cask "alfred"
cask "omnifocus"
# istat menus fails to install due to no sha256 associated with the pkg
# cask "istat-menus"
cask "netnewswire"
cask "bbedit"
cask "bartender"
cask "spamsieve"
cask "mailmate"
cask "gpg-suite"
cask "visual-studio-code"

brew "starship"
brew "stow"
brew "gh"
